### ISSUE TITLE
Prediction

### ISSUE THREAD

**Issue by mrkasri** [dennybritz/cnn-text-classification-tf#117]
Hi, how to predict a new text label ?

**Comment by liangtingStduy** [comment]
This is an automatic reply,confirming that your e-mail was received.Thank you!-------------------------------------liangting

**Comment by xuqiangxq** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xuqiangxq** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by liangtingStduy** [comment]
This is an automatic reply,confirming that your e-mail was received.Thank you!-------------------------------------liangting
