### ISSUE TITLE
run it on SGE grid?

### ISSUE THREAD

**Issue by galactica147** [dennybritz/cnn-text-classification-tf#14]
Hi Denny, when I tried 'train.py', it seems to be running on a single machine. 
Is it possible to configure tensorflow so that it runs on a grid, say the SGE grid? 
Please advise. thanks!

**Comment by dennybritz** [comment]
The newest release (http://googleresearch.blogspot.com/2016/04/announcing-tensorflow-08-now-with.html) supports distributed training, you could look into that. It's not part of this code though.

**Comment by albertz** [comment]
Some related discussion is [in this TF upstream issue](https://github.com/tensorflow/tensorflow/issues/7068).
