### ISSUE TITLE
AttributeError: _parse_flags

### ISSUE THREAD

**Issue by CarbuncleOrigin** [dennybritz/cnn-text-classification-tf#158]
I've finished running train.py but when i run eval.py i get this error. Can you help me with this?
Traceback (most recent call last):
  File "./eval.py", line 31, in <module>
    FLAGS._parse_flags()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\tensorflow\python\platform\flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\absl\flags\_flagvalues.py", line 470, in __getattr__
    raise AttributeError(name)
AttributeError: _parse_flags

**Comment by Hind-Almerekhi** [comment]
Hi,
I had the same issue and managed to solve it by doing the following:
replace FLAGS._parse_flags() with
import sys
FLAGS(sys.argv)

Then run the eval.py script as instructed by the readme file. 

Hope it helps!

**Comment by CarbuncleOrigin** [comment]
thanks

**Comment by usmaann** [comment]
Hi
where to replace below files

replace FLAGS._parse_flags() with
import sys
FLAGS(sys.argv

**Comment by Hind-Almerekhi** [comment]
Hello
You don't need to replace any files, just replace this line of code in the file eval.py:
FLAGS._parse_flags()

with the following lines:
import sys
FLAGS(sys.argv)

Then you should be able to run the eval.py code with no problems. 

I hope it's clear now.
