### ISSUE TITLE
fail while trying to inference a encoded sentence 

### ISSUE THREAD

**Issue by laesunk** [dennybritz/cnn-text-classification-tf#16]
im trying to inference trained model with raw_input(stdin). it is encoded and padded as same as processing training  data
but fail. 
error message is bellow 
tensorflow.python.framework.errors.InvalidArgumentError: input must be 4-dimensional[100,128,1]
(i filxed sentence length 100 and embeding128)
but bulk inference works.
how can i fix it?

**Comment by dennybritz** [comment]
The model works on batches of sentences, not on a single sentence. So in your case the batch dimensions is missing. Your dimensions should be `[1,100,128,1]` instead of `[100,128,1]`. You can use `tf.expand_dims` to add an extra dimension: https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#expand_dims

**Comment by laesunk** [comment]
so i add a dimension like below. 
self.embedded_chars_expanded = tf.expand_dims(self.embedded_chars, 0)
but dimension error happened. is there any other issue?

**Comment by laesunk** [comment]
thank you advice. finally i trained model with my own data. then I tired to evaluate model with sentence that i typed. so I I've add some codes to get input from console(terminal)
while True:
    inputTxt = raw_input('input for test")
    inputTxt = forencoding(inputTxt, vocab)
    sess.run(prediction , {input_x: inputTxt}

first time it gives me a result of prediction. 
but fail in sencond tyring. 
error is  typeerror  in session.py.  please see below
it seems session have previous result. 
is it really type error? 
thanks in advance

==========================================================
please input to test : good
[good]
[[-2.87885094  3.4977808 ]
 [-2.87885094  3.4977808 ]]
please input to test : good
[good]
Traceback (most recent call last):
  File "test_eval_word.py", line 223, in <module>
    scores = sess.run(scores, {input_x: testVec, dropout_keep_prob:1.0})
  File "/home/tech/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/home/tech/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 523, in _run
    processed_fetches = self._process_fetches(fetches)
  File "/home/tech/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 493, in _process_fetches
    % (subfetch, fetch, type(subfetch), str(e)))
TypeError: Fetch argument array([[-2.87885094,  3.4977808 ],
       [-2.87885094,  3.4977808 ]], dtype=float32) of array([[-2.87885094,  3.4977808 ],
       [-2.87885094,  3.4977808 ]], dtype=float32) has invalid type <type 'numpy.ndarray'>, must be a string or Tensor. (Can not convert a ndarray into a Tensor or Operation.)
