### ISSUE TITLE
size of maxpooling 

### ISSUE THREAD

**Issue by yongzhuo** [dennybritz/cnn-text-classification-tf#184]
why ksize of maxpooling of textcnn is [1, self.sentence_size - filter_size + 1, 1, 1]，what I mind is "sentence_size - filter_size + 1", can it be sentence_size, filter_size or any others, is there any tricks？ I couldn't see it in paper.

**Comment by lpq29743** [comment]
Since the convolutional layer of CNN use the "VALID" padding, the dimension of the convolutional output is "sentence_size - filter_size + 1". That's why use "sentence_size - filter_size + 1".

**Comment by yongzhuo** [comment]
ok, thanks!
