### ISSUE TITLE
Generating error for other language dataset

### ISSUE THREAD

**Issue by vinayakumarr** [dennybritz/cnn-text-classification-tf#20]
Please check. it generates the following error for other language dataset

 File "train.py", line 158, in <module>
    x_batch, y_batch = zip(*batch)
ValueError: need more than 0 values to unpack

**Comment by dennybritz** [comment]
It seems like there are errors in your code that created the batch. Would need more details.

**Comment by vinayakumarr** [comment]
I am using your code only i just changed the dataset. (Instead of your english i am using some other language)

**Comment by vinayakumarr** [comment]
running your code in python 2.7. Because of this problem, i am getting error. Could you please tell us how to correct this

**Comment by dennybritz** [comment]
If you changed the dataset you also need to change the dataset loading code. I don't think this is a problem with the code in the repository, but rather a problem with your Python code. So I'd recommend posting it on Stackoverflow instead of here and get help here.
