### ISSUE TITLE
AttributeError: 'module' object has no attribute 'layers'

### ISSUE THREAD

**Issue by emraht** [dennybritz/cnn-text-classification-tf#21]
Hello,
I get this error when i try to train with the existing data on AWS, any ideas on this? 

Traceback (most recent call last):
  File "./train.py", line 73, in <module>
    l2_reg_lambda=FLAGS.l2_reg_lambda)
  File "/home/ubuntu/username/cnn-text-classification-tf/text_cnn.py", line 69, in __init__
    initializer=tf.contrib.layers.xavier_initializer())
AttributeError: 'module' object has no attribute 'layers'

I have no problems with TF installation, the examples run just fine.
Thanks!

**Comment by dennybritz** [comment]
Seems like a Tensorflow version mismatch. Is that 0.8?

**Comment by emraht** [comment]
It was 0.6, updated to 0.8 and now working!
Thanks..
