### ISSUE TITLE
Error with python 3

### ISSUE THREAD

**Issue by rajmiglani** [dennybritz/cnn-text-classification-tf#22]
Can it be run in a jupiter notebook with just python 2 kernel installed?
I am facing  errors as:It shows ArgumentError: argument --embeding_dim: conflicting option string(s): --embeding_dim

tf.flags.DEFINE_integer("embedding_dim", 128, "Dimensionality of character embedding (default: 128)")
     14 tf.flags.DEFINE_string("filter_sizes", "3,4,5", "Comma-separated filter sizes (default: '3,4,5')")
     15 tf.flags.DEFINE_integer("num_filters", 128, "Number of filters per filter size (default: 128)")

/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_flags.pyc in DEFINE_integer(flag_name, default_value, docstring)
     82     docstring: A helpful message explaining the use of the flag.
     83   """
---> 84   _define_helper(flag_name, default_value, docstring, int)
     85 
     86 

Kindly help .

**Comment by dennybritz** [comment]
I haven't seen this before, but the code was written for Python 3 and Tensorflow 0.8, so make sure you have those.

**Comment by rajmiglani** [comment]
Hey,Thanks for a reply.
Its working fine now(even on python 2)
But can you be more precise as to how to test the model?
i have successfully trained the model but am unable to test it.
I have tried to change the files in data_helpers.py(changed rt-polarity files) but then too i am not getting any new results.i also tried printing all_predictions in eval.py.
Kindly help.
