### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by rajmiglani** [dennybritz/cnn-text-classification-tf#23]
Hey i have successfully trained the model but am unable to test it.
I have tried to change the files in data_helpers.py(changed rt-polarity files) but then too i am not getting 
any new results.i also tried printing all_predictions in eval.py.
Kindly help.

**Comment by dennybritz** [comment]
Can you be more specific what the problem is when testing with `eval.py`?

**Comment by rajmiglani** [comment]
Hey,
Thanks for the reply.
I am getting many errors:

First i am using jupyter notebook,
then when i had trained i removed the Flag part of the file,
n now on evaluating via eval.py when i do remove the flag part it gives me error as : checkpoint_dir not defined(i removed the FLAGS.check_dir to only checkpoint_dir)
Also on closing the notebook and opening to run it again i can now run train.py even with the flag part but not the eval.py file. it gives flag error with using flag part and if i remove it gives the same as mentioned above.
also once again when i run the eval file(after reopening ) i get yet another error when using flag part as:
OSError:File None.meta does not exixt

Can you please look into the issue?

**Comment by dennybritz** [comment]
This seems like an error in your Python code, and not something that's caused by a bug in the repository code. I'd suggest posting your code on Stackoverflow and getting help there, I'd like to keep the issues here related to the repository itself.

**Comment by saurabhzuve** [comment]
@rajmiglani were you able to resolve your issue?

**Comment by rajmiglani** [comment]
Yeah i was able to figure it out. Thanks for the suggestions @saurabhzuve.

**Comment by wakamd** [comment]
Hi gang.
I had the same issue and tried this: checkpoint_file = tf.train.latest_checkpoint(FLAGS.checkpoint_dir,"/home/me/cnn/runs/1518703649/checkpoints/") but still get the same error: IOError: File None.meta does not exist.
How do I solve this? am still learning this .
Regards

**Comment by jaggi** [comment]
@wakamd did you find the solution??

**Comment by wakamd** [comment]
Yes. Reinstalling python and checking the actual check_point directory/path
solved it.

**Comment by jaggi** [comment]
did you gave the same directory as u mentioned in the above comment??

**Comment by osamakhalid24** [comment]
Hi @wakamd can you please elaborate the solution? I tried to give path to vocab file but the error is still the same

**Comment by osamakhalid24** [comment]
well I figured it out, anyone facing a problem, you need to change this in eval file 
        saver = tf.train.import_meta_graph("{}.meta".format(checkpoint_file))
        saver.restore(sess, checkpoint_file)

with this
saver = tf.compat.v1.train.import_meta_graph("{}.meta".format("./runs/1566473224/checkpoints/model-30000"))
        saver.restore(sess, "./runs/1566473224/checkpoints/model-30000")

**Comment by wakamd** [comment]
I have been away for some time. Just checking on my project with CNN. @osamakhalid24 , thanks for the update. It works.
