### ISSUE TITLE
 Cannot feed value of shape

### ISSUE THREAD

**Issue by UTH** [dennybritz/cnn-text-classification-tf#24]
hi, am trying to testdrive the code in linux, it runs good. 
but when I use 390 lines only sample data to eval, it shows error:

> ValueError: Cannot feed value of shape (390, 47) for Tensor 'input_x:0', which has shape '(?, 56)'

should I modify the function below? :
`pred_y = sess.run(predictions, {input_x: x_test, dropout_keep_prob: 1.0})`

Any help would be appreciated

**Comment by rajmiglani** [comment]
No you don't need to change that.
Can you be more clear with the error traceback?

**Comment by UTH** [comment]
Hi @rajmiglani 
I modified the data_helpers.py and add a new function which similar to load_data() and some else.
so that it could load test_x data from the test.txt which contains the sample lines.
###
def new_data():
    # Load and preprocess data
    sentences = get_new_data() # this function returns x only, no label y.
    sentences_padded = pad_sentences(sentences)
    vocabulary, vocabulary_inv = build_vocab(sentences_padded)
    x = build_input(sentences_padded, vocabulary)
    return [x, vocabulary, vocabulary_inv]`
###
by prepare the test.txt below:
`tail -n 160 rt-polarity.neg >test.txt && tail -n 130 rt-polarity.pos >>test.txt`

**Comment by UTH** [comment]
solved: sequence_length should be set by the raw data.

**Comment by sonu107** [comment]
Facing the same error, What is sequence_length should be set by raw data mean @UTH
