### ISSUE TITLE
Re-training the model with more data

### ISSUE THREAD

**Issue by rajmiglani** [dennybritz/cnn-text-classification-tf#26]
Hey @dennybritz  i have a trained model but i have more dataset available.Do i need to re train the model with the whole data(prev +  new) or is there any method to train the pre trianed model with new data(say intitialy i had 400 q and now i have 5 more)?

**Comment by dennybritz** [comment]
It's recommended to re-train with all the data, but in theory you could just re-train a few iteration with your new data. There isn't support for this in the code, but you can load the model just like in `eval.py` and then train a few iterations with your data just like in `train.py`.
