### ISSUE TITLE
Transfer Learning?

### ISSUE THREAD

**Issue by pfrcks** [dennybritz/cnn-text-classification-tf#32]
Hi,

Is there anyway I can utilise this for Transfer Learning? I mean, if I train the model on the rt data, can I then used the trained model to perform text classification on a different dataset?

PS: Thanks for this awesome repo and the blog ! :)

**Comment by dennybritz** [comment]
Yes, you can classify unseen data with the model. However, if your new data has words that didn't occur in the training set the model won't perform well.

Transfer learning usually means that you want to train on dataset 1, save the weights, and then initialize the model with some of the saved weights before training on another dataset 2. You can do this too, check out the Tensorflow tutorial on saving/restoring: https://www.tensorflow.org/versions/r0.9/how_tos/variables/index.html#variables-creation-initialization-saving-and-loading

**Comment by pfrcks** [comment]
@dennybritz Hey, thanks for the input. It really helped me.
If it's not too much can I ask one more thing? 
If I wanted to see which features contributed the most to the classification, is there any way I can find them? 
For example, in the case of sentiment classification on the movie dataset, can I find in any way which features contributed the most for the successful classification?

I'm sorry for causing so much trouble, but I thought since you have worked on it in depth maybe you could answer my query.

Thanks.

**Comment by dennybritz** [comment]
Generally speaking, it's not obvious how to extract what kind of features are learned by a CNN. There are several approaches to this I recommend checking out the following:

- https://arxiv.org/abs/1311.2901
- http://cs231n.github.io/understanding-cnn/
- http://cs231n.stanford.edu/slides/winter1516_lecture9.pdf

All these are for image recognition, but you can apply many of the same techniques to text.

**Comment by pfrcks** [comment]
@dennybritz Thanks for the links. I'll look into them :)

**Comment by rebeen** [comment]
thanks for both of you it is really interesting for me I am working on Unsupervised Transfer learning but this  should be also useful for me becuase I just started Transfer learning and I only have a theoretical idea about it not practice so  please if you have any experience or anything else please share with me thank you again
