### ISSUE TITLE
Including word2vec?

### ISSUE THREAD

**Issue by pfrcks** [dennybritz/cnn-text-classification-tf#34]
Hi Denny,

I wanted to ask you how can I go about integrating word2vec word embeddings in this model instead of learning them from scratch. As mentioned in Yoon Kim's paper, word2vec embeddings perform better than those learned from scratch and I wanted to utilize that.
Can you please help me?

**Comment by dennybritz** [comment]
#17

**Comment by pfrcks** [comment]
Thanks :)
