### ISSUE TITLE
Getting error on train.py line #16

### ISSUE THREAD

**Issue by thirumalaipm** [dennybritz/cnn-text-classification-tf#45]
Hi,

Thanks for providing this script. While I am trying train.py script and I am getting below error.

> ArgumentError                             Traceback (most recent call last)
<ipython-input-5-d23abe801981> in <module>()
     14 
     15 # Model Hyperparameters
---> 16 tf.flags.DEFINE_integer("embedding_dim", 128, "Dimensionality of character embedding (default: 128)")
     17 tf.flags.DEFINE_string("filter_sizes", "3,4,5", "Comma-separated filter sizes (default: '3,4,5')")
     18 tf.flags.DEFINE_integer("num_filters", 128, "Number of filters per filter size (default: 128)")

> /usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.pyc in DEFINE_integer(flag_name, default_value, docstring)
     83     docstring: A helpful message explaining the use of the flag.
     84   """
---> 85   _define_helper(flag_name, default_value, docstring, int)
     86 
     87 

> /usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.pyc in _define_helper(flag_name, default_value, docstring, flagtype)
     57                               default=default_value,
     58                               help=docstring,
---> 59                               type=flagtype)
     60 
     61 

I am using Tensorflow version 0.11.0rc2 and python version 2.7.6. Please let me know how to solve this issue.

Many Thanks, Thirumalai M

**Comment by dennybritz** [comment]
This repository clearly states Python 3 as a requirement.

**Comment by thirumalaipm** [comment]
Thanks Dennybritz.
