### ISSUE TITLE
Purpose of line 31 in train.py

### ISSUE THREAD

**Issue by ylhsieh** [dennybritz/cnn-text-classification-tf#5]
In the beginning, I am a bit confused about the purpose of this line, namely, 
`FLAGS.batch_size`
Later I guess this is to make the parameter printing work? Because I removed it and the parameters won't print. Anyway, I found that using `FLAGS._parse_flags()` would work and is probably more clear. Just thought you would like to know.

**Comment by dennybritz** [comment]
Yeah, the parameters are parsed lazily, so I had to access them before I can print them. Thanks for letting me know, I didn't know about `FLAGS._parse_flags()`. That's much cleaner!
