### ISSUE TITLE
Loading a checkpoint and classifying new data

### ISSUE THREAD

**Issue by LeapGamer** [dennybritz/cnn-text-classification-tf#6]
How do I load one of my checkpoints and get a prediction on new data? I looked around in past issues and see https://github.com/dennybritz/cnn-text-classification-tf/issues/2 but I wasn't sure how to load in the checkpoint first.

**Comment by dennybritz** [comment]
You'd need to instantiate the model (with the same parameter) and then use the load checkpoint method of the saver. Check out the TF tutorial on that topic: https://www.tensorflow.org/versions/v0.6.0/how_tos/variables/index.html#variables-creation-initialization-saving-and-loading

**Comment by CyrusChiu** [comment]
Thanks for @dennybritz , I've already trained a text cnn on my own dataset. 
Following code allows for get a prediction on your own data.
```
def predict_step(x_batch, y_batch):
    """
    predict on a test set
    """
    feed_dict = {
      cnn.input_x: x_batch,
      cnn.input_y: y_batch,
      cnn.dropout_keep_prob: 1.0
    }
    y_pred = sess.run(
        [cnn.y_pred], feed_dict)
    return y_pred

ckpt = tf.train.get_checkpoint_state('path/to/your/ckpt_file')
saver.restore(sess, 'path/to/your/ckpt_file')
```

**Comment by imissedaplane** [comment]
@CyrusChiu are you adding this def to train.py? I loaded the ckpt file in using:

`import tensorflow as tf

x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

w = tf.Variable(tf.zeros([1, 1], dtype=tf.float32))
b = tf.Variable(tf.ones([1, 1], dtype=tf.float32))
y_hat = tf.add(b, tf.matmul(x, w))


saver = tf.train.Saver()  # defaults to saving all variables - in this case w and b

with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    ckpt = tf.train.get_checkpoint_state('./model/path')
    if ckpt and ckpt.model_checkpoint_path:
        saver.restore(sess, ckpt.model_checkpoint_path)
    else:
            "...no checkpoint found..."

    # Now you can run the model to get predictions
    batch_x = './batch/path'
    predictions = sess.run(y_hat, feed_dict={x: batch_x})

    print (predictions)`

but it errors with ValueError: could not convert string to float: ./runs/batchtest. I think I need to use the text cnn in here?

**Comment by dennybritz** [comment]
See #8
