### ISSUE TITLE
issues regarding the version of python 3

### ISSUE THREAD

**Issue by haridatascientist** [dennybritz/cnn-text-classification-tf#7]
i installed tensor flow in my python 3.4 version and i tried to run the cnn-text classification -tf code. but i got error in data input say (x_train, y_train).  how to make this code compatible to version 3.4.

**Comment by dennybritz** [comment]
I'm not sure. Can you post the exact error and stack trace?

**Comment by sjhddh** [comment]
Hey @haridatascientist I've transferred @dennybritz 's code into python3 version, and it's running perfectly now. I've had several trail and errors before, so I think I might know the solution to your problem. Would you mind send the detailed error and stack trace?

**Comment by dennybritz** [comment]
I just converted the code to Python 3 as well.
