### ISSUE TITLE
Resource exhausted, OOM errors

### ISSUE THREAD

**Issue by shahbazsyed** [dennybritz/cnn-text-classification-tf#76]
I am trying to run this code on GPU. This is the output of nvidia-smi 

![image](https://cloud.githubusercontent.com/assets/4356098/23571938/3d831340-006c-11e7-9f0d-8ca9943dc1f2.png)

This is the part of the code I changed in text_cnn.py

`import os`
`os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"`
`os.environ["CUDA_VISIBLE_DEVICES"] = "1,2"`
`import tensorflow as tf`
`import numpy as np`

```
 # Embedding layer
        with tf.device('/gpu:0'), tf.name_scope("embedding"):
            W = tf.Variable(
                tf.random_uniform([vocab_size, embedding_size], -1.0, 1.0),
                name="W")
            self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)
            self.embedded_chars_expanded = tf.expand_dims(self.embedded_chars, -1)
```

I also removed all the summary_ops and writers from train.py . Everything else is as it is from the repo.

The error I get when run python train.py is this

![image](https://cloud.githubusercontent.com/assets/4356098/23572270/2e48b9c8-006e-11e7-8671-a57a7a353217.png)

Can someone kindly tell me what  am I doing wrong here? 

I am running this inside the latest tensorflow:gpu docker container on Ubuntu.

**Comment by cahya-wirawan** [comment]
Probably your gpu doesn't have enough memory for the training. Try to reduce the batch size from the default 64 to 32 or smaller until it doesn't crash. If it crash also during the evaluation, try to reduce the dev_sample_percentage from 0.1 to 0.05 or lower.

**Comment by shahbazsyed** [comment]
@cahya-wirawan Thanks for the suggestion. I found my mistake. The actual problem was caused by other open programs in my Jupyter notebook! As [tensorflow](https://www.tensorflow.org/tutorials/using_gpu) specifically mentions that they do not release the GPU memory to prevent fragmentation errors, I closed all other active kernels in my notebook and then ran this script. It works just fine now.

**Comment by behnazeslami** [comment]
[bare_train_news_article_wikipedia.txt](https://github.com/dennybritz/cnn-text-classification-tf/files/1484845/bare_train_news_article_wikipedia.txt)
@dennybritz I'm using 2 different datasets (1. Full_Economic_News [7775 documents] // 2.News_Article_Wikipedia [3000 documents]) after running ./train.py after steps 100 suddenly process becomes kill and stop!!!! 
How can I solve this issue?
I attached my 2 datasets.
[Full-Economic-News.txt](https://github.com/dennybritz/cnn-text-classification-tf/files/1484844/Full-Economic-News.txt)
[bare_train_news_article_wikipedia.txt](https://github.com/dennybritz/cnn-text-classification-tf/files/1484847/bare_train_news_article_wikipedia.txt)
