### ISSUE TITLE
why the number of batch is calculated with len(data) - 1?

### ISSUE THREAD

**Issue by akYoung** [dennybritz/cnn-text-classification-tf#85]
I suppose`num_batches_per_epoch = int (len(data)/batch_size))` is enough, but why is it written as `num_batches_per_epoch = int((len(data)-1)/batch_size) + 1`?

**Comment by lgalke** [comment]
`(a-1)/b+1` is a typical rounding scheme used in numerics. Assume `a=101, b=25`, you intuitively need 5 batches per epoch of sizes: `[25, 25, 25, 25, 1]`. By just using floored division (that is what `int(a/b)` does) you would get `101/25 = 4` batches and would leave out the 1 remaining sample. Instead, with the $-1, +1$ magic, you get `(100-1)/25 + 1 = 5` number of batches per epoch, as desired.
Considering the other corner case `125,25` should lead to 5 batches. Thus by computing `(125-1)/25 + 1 = 4 + 1 = 5`, we also obtain the desireed result.

**Comment by akYoung** [comment]
@lgalke  ok, got it! Thanks a lot.
